name: Muscle Maker Grill - Olathe
favicon: null
layout_spectrum: 0.49986444134265184
typography_spectrum: 0.03605286544188857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.721318090101704
  lightness: 0.571199243189767
  saturation: 0.6932206915225834
  rhythmicContrast: 0.12688723346218467
purpose: []
